version: "3"
services:
  node:
    build: ./docker/node
    volumes:
      - ./vue:/var/www/html/
    working_dir: /var/www/html/gin-vue
    command: yarn start
    ports:
      - "3000:3000"
  db:
    image: mysql:5.7.22
    environment:
      MYSQL_DATABASE: sample_db
      MYSQL_USER: test_user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3306:3306"
  api:
    build: ./docker/api
    volumes:
      - ./api:/go/src/api
  nginx:
    build: ./docker/nginx
    ports:
      - "1234:1234"